apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: mysql
  labels:
    app: mysql
    component: mysql
spec:
  type: NodePort
  selector:
    app: mysql
    component: mysql
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30006
