apiVersion: v1
kind: Service
metadata:
  name: zk-svc
  namespace: kafka
  labels:
    app: zk
    component: kafka
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: zk
    component: kafka
